name: CI

on:
 workflow_dispatch:
 
jobs:
  Docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
          registry: ${{ steps.registry_url.outputs.prop }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}          
      - run: |
          docker build --tag ${{ steps.registry_url.outputs.prop }}/${{ steps.appcode.outputs.prop }}/${{ steps.app_name.outputs.prop }}:${{ env.TAG }} .
