name: CI

on:
 workflow_dispatch:
 
jobs:
  Docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
          registry: philtechsb.azurecr.io
          appcode: pbsb
          image: ubuntu/tomee
          username: philtechsb
          password: ecXARVhWjVnQs5EAMa9N9taTuLSrwfoRn4F5lAgYBw+ACRD04CgO          
      - run: |
          docker build --tag ${{ steps.registry.outputs.prop }}/${{ steps.appcode.outputs.prop }}/${{ steps.image.outputs.prop }}:${{ env.TAG }} .
