name: CI

on:
 workflow_dispatch:
 
jobs:
  Docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
          registry: philtechsb.azurecr.io
          username: User
          password: Abc123          
      - run: |
          docker build --tag ${{ steps.registry_url.outputs.prop }}:${{ env.TAG }} .
