name: CI

on:
 workflow_dispatch:
  inputs:
   ACTIONSFILE:    
        required: false
        type: string
   TAG:
     required: false
     type: string
env: 
  ACTIONSFILE: ${{ inputs.ACTIONSFILE }}
  TAG: ${{ inputs.TAG }}    
 
jobs:
  Docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
          registry: philtechsb.azurecr.io
          username: philtechsb
          password: ecXARVhWjVnQs5EAMa9N9taTuLSrwfoRn4F5lAgYBw+ACRD04CgO
          tags: philtechsb.azurecr.io/pbsb/ubuntu/tomee:${{ env.TAG }}
