name: CI

on:
 workflow_dispatch:
 
env: 
  ACTIONSFILE: Actionsfile/sample
  TAG: np-${{ github.run_id }}-${{ github.run_number }}
jobs:
  Docker_build:
    runs-on: [ jenkins-sl1 ]
    steps:
      - uses: actions/checkout@v2    
      - name: Download Artifact Jarfile.
        uses: actions/download-artifact@v2
        with:
          name: AppArtifacts               
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
          registry: ${{ steps.registry_url.outputs.prop }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}          
      - run: |
          docker build --tag ${{ steps.registry_url.outputs.prop }}/${{ steps.appcode.outputs.prop }}/${{ steps.app_name.outputs.prop }}:${{ env.TAG }} .
