name: CI

on:
 workflow_dispatch:
 
env: 
  ACTIONSFILE: Actionsfile/sample
  TAG: np-${{ github.run_id }}-${{ github.run_number }}
jobs:
  Docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
         push: true        
         tags: philtechsb.azurecr.io/pbsb/ubuntu-latest:${{ github.sha }}
