name: CI

on:
 workflow_dispatch:
 
jobs:
  Docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build     
        uses: PhiltechSandbox/Docker-login@main
        with:
          registry: philtechsb.azurecr.io
          username: philtechsb
          password: ecXARVhWjVnQs5EAMa9N9taTuLSrwfoRn4F5lAgYBw+ACRD04CgO          
      - run: |
          docker build --tag philtechsb.azurecr.io:${{ env.TAG }} .
