name: oneclick-cicd-nonprod
on:
  workflow_dispatch:
    inputs: 
      dev:
        type: boolean
        description: 'deploy dev'    
        required: false
        default: 'false'          
      qa1:
        type: boolean
        description: 'deploy qa1'    
        required: false
        default: 'false'   
  
jobs:
  Extract_branch: 
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/extractbranch.yml@master
  call-ci-workflow:
    needs: Extract_branch
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-ci-nonprod-war.yml@master
    with:
      ACTIONSFILE: "Actionsfile/dev"
      TAG: np-${{ github.run_id }}-${{ github.run_number }}
      build_type: maven
      javaVersion: 8
      VERACODE_APPNAME: rcdo
      branch_name: "${{ needs.Extract_branch.outputs.branch_name }}"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      TL_USERNAME: ${{ secrets.TL_USERNAME }}
      TL_PASSWORD: ${{ secrets.TL_PASSWORD }}
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      VERACODEID: ${{ secrets.VERACODEID }}
      VERACODEKEY: ${{ secrets.VERACODEKEY }}
      
  dev-deploy:
    needs: call-ci-workflow
    if: success() && github.event.inputs.dev == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/dev"
      TAG: np-${{ github.run_id }}-${{ github.run_number }}     
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-dev:
    needs: dev-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/dev" 
    secrets:  
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }}   
  qa1-deploy:
    needs: call-ci-workflow
    if: success() && github.event.inputs.qa1 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa1"
      TAG: np-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-qa1:
    needs: qa1-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa1" 
    secrets:   
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }}
  qa2-deploy:
    needs: call-ci-workflow
    if: success() && github.event.inputs.qa2 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa2"
      TAG: np-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-qa2:
    needs: qa2-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa2" 
    secrets:   
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }}    
  perf1-deploy:
    needs: call-ci-workflow
    if: success() && github.event.inputs.perf1 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/perf1"
      TAG: np-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-perf1:
    needs: perf1-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/perf1" 
    secrets:   
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }}   
  stage-deploy:
    needs: call-ci-workflow
    if: success() && github.event.inputs.stage == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/stage"
      TAG: np-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-stage:
    needs: stage-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/stage" 
    secrets:   
      KUBECONFIG: ${{ secrets.ESCO_AKSBA2_NONPROD_WESTUS_CLUSTER_01 }}  
